### ISSUE TITLE
Fuzzy Expressions: Brazilian Portuguese (pt_BR)

### ISSUE THREAD

**Issue by distantnative** [distantnative/kirby-relativedate#20]
To realize fuzzy expressions, translations for each language for the following terms is necessary:

```php
 'next'        => 'next |:reference|', // as in 'next week' or 'next Thursday'
 'last'         => 'last |:reference|', // as in 'last week' or 'last Thursday'

'today' => 'today',
'1day'  => array('tomorrow','yesterday'),

'Mon'   => 'Monday',
'Tue'   => 'Tuesday',
'Wed'   => 'Wednesday',
'Thu'   => 'Thursday',
'Fri'   => 'Friday',
'Sat'   => 'Saturday',
'Sun'   => 'Sunday',

'week'  => 'week',
'month' => 'month',
```

If you can help, that would be awesome!

**Comment by rhawbert** [comment]
I wonder about week days in pt_BR we have short and long versions, i.e.:
   monday, 
   short = segunda
   long: segunda-feira

but weekends have only one version:
   saturday = sábado
   sunday = domingo

**Comment by distantnative** [comment]
In my view, fuzzy expressions usually would used to keep it short. If the short versions work and don't seem so odd, I'd go with them. But if it'd feel weird in a lot of situations to have them, just stick with the long ones.

**Comment by rhawbert** [comment]
I'll stick with the short versions then... 

```php
 'next'        => 'próxima |:reference|', // as in 'next week' or 'next Thursday'
 'last'         => 'última |:reference|', // as in 'last week' or 'last Thursday'

'today' => 'hoje',
'1day'  => array('amanhã','ontem'),

'Mon'   => 'Segunda-feira',
'Tue'   => 'Terça-feira',
'Wed'   => 'Quarta-feira',
'Thu'   => 'Quinta-feira',
'Fri'   => 'Sexta-feira',
'Sat'   => 'Sábado',
'Sun'   => 'Domingo',

'week'  => 'semana',
'month' => 'mês',
```

**Comment by rhawbert** [comment]
Another problem/exception... the weekdays kinda have genders, weekdays are "female" and weekends are "male" when referred by the 'next' and 'last' fuzzys. 

The correct way would be to create exceptions for the weekends,  which would look like:

```php
 'next'        => 'próximo |:reference|', // weekend is male 
 'last'         => 'último |:reference|', // weekend is male 
```

**Comment by distantnative** [comment]
Ah yea, I also ran into that question/issue. At the moment there is no way, so we have to go for a compromise:

```php
 'next'        => 'próximo/a |:reference|',
 'last'         => 'último/a |:reference|',
```

Maybe? I have this def on my list of things that should be done better :) Thanks already!

**Comment by rhawbert** [comment]
I see no problem. 
Common internationalisation hassle from the interwebz.
Cheers. :+1:

**Comment by distantnative** [comment]
@rhawbert I think I will have a way to deal with male/female versions in v1.1, so did I get it right: weekdays are female, weekends male, semana is female and mes is male?

**Comment by rhawbert** [comment]
> weekdays are female, weekends male, semana is female and mes is male?
> And it would be próximo and próxima, as well as, último and última?

Exactly.

**Comment by distantnative** [comment]
Great, thanks again!
