### ISSUE TITLE
Cannot Use 'kirbytext()' and 'kirbytag()' with 'threshold' Option

### ISSUE THREAD

**Issue by luxlogica** [distantnative/kirby-relativedate#57]
I'm trying to use RelativeDate on a Kirby *date* field. Although I cannot chain the method directly to the date field, according to the docs here I should be able to do this, either by using Kirby's *kirbytext()* function...:

``` php
<?php echo kirbytext('relativedate: ' . $page->date('Y-m-d') . ')') ?>
```

...or - supposedly - by using the equivalent *kirbytag()* function:

```php
<?php echo kirbytag(array('relativedate' => $page->date('Y-m-d'))) ?>
```

This works fine, until we add a **threshold** setting - for instance:

```php
<?php 
    echo kirbytag(array(
        'relativedate' => $page->date('Y-m-d'),
        'threshold' => 604800
    ))
 ?>
```

It then errors out. The output says that the error is on line 64 of *'relativedate.php'* - it states that the variable *$field* is undefined.

This, of course, also fails if you set the threshold option globally in config:

``` php
c::set('relativedate.threshold', 604800);
```

So right now it seems that if you need 'threshold', there is no way to use RelativeDate with Kirby's date field... :(

**Comment by luxlogica** [comment]
Temporary hack/workaround:

``` php
<?php 
    $days = 20;
    if(($page->date('U') + (60 * 60 * 24 * $days)) > date('U')){
            echo kirbytag(array('relativedate' => $page->date('Y-m-d')));
        } else {
            echo $page->date('l, d M Y');
    }
?>
```

**Comment by distantnative** [comment]
Ah, I think I found the mistake, but I'm traveling atm so I'll only be able to update the repo on the weekend. But maybe you can test, if it's actually a proper fix.

Could you try to replace line 64 in relative-date.php?

```php
// old
        abs(strtotime($field->value) - time()) <= $args['threshold']) {

// new, this should fix it - replace the above with the following:
        abs(strtotime($tag->attr('relativedate')) - time()) <= $args['threshold']) {
```

Does that work for you?

**Comment by luxlogica** [comment]
Yes, that seems to have fixed it!
